### ISSUE TITLE
Partial matches keep captured variables on the stack

### ISSUE THREAD

**Issue by alecthomas** [PuerkitoBio/pigeon#1]
Hello,

First, Pigeon is awesome. The most well documented and maintained PEG generator for Go that I've found. Thanks!

The following example produces `foo.foo`, where (IIUC) it should produce `(nil).foo`:

```
{
package main

func main() {
  ast, err := Parse("STDIN", []byte("foo"))
  if err != nil {
    fmt.Printf("error: %s\n", err)
    return
  }
  fmt.Printf("%+v\n", ast)
}
}

TableRef <- (database:Id '.')? table:Id    { return fmt.Sprintf("%v.%v", database, table), nil }
Id <- [a-z]+                               { return c.text, nil }

```

I'm assuming this occurs because the optional sub-expression partially matches, populates the stack, but does not clean up when the rest of the match fails.

Thanks,
Alec

**Comment by PuerkitoBio** [comment]
Hey Alec,

Thanks for this, pigeon is still very very young and alpha-level (barely a few weeks old!) and I'm glad to have some other pair of eyes on this to raise issues. In this case, the `database` label should not even be allowed in the code block (it would be if it was written like this:

```
TableRef <- database:(Id '.')? table:Id {...}
```

So I'll add a test case and a fix for that.

**Comment by alecthomas** [comment]
Aha! Thank you, that fixed it!

**Comment by alecthomas** [comment]
Though, if labels aren't allowed in subexpressions, that would seem to make extracting values more onerous. eg.

```
TableRef <- database:(Id '.')? table:Id (AS alias:Id)? { return fmt.Sprintf("%s.%s AS %s", database, table, alias), nil }
```

would have to become:

```
TableRef <- database:(Id '.')? table:Id alias:Alias? { return fmt.Sprintf("%s.%s AS %s", database, table, alias), nil }
Alias <- AS alias:Id { return alias, nil }
```

Is that correct?

**Comment by alecthomas** [comment]
Actually it's even more convoluted. You'd need to also split out database so you don't capture the period:

```
TableRef <- database:Database? table:Id alias:Alias? { return fmt.Sprintf("%s.%s AS %s", database, table, alias), nil }
Database <- database:Id '.' { return database, nil }
Alias <- AS alias:Id { return alias, nil }
```

**Comment by PuerkitoBio** [comment]
`TableRef <- database:(Id '.')? table:Id (AS alias:Id)?`

could become

`TableRef <- database:(Id '.')? table:Id alias:(AS Id)?`

then it's just a matter of testing the value and extracting the right index (a sequence expression is a `[]interface{}`, so to get the Id in AS Id, you convert to []interface{} and get index 1.

Tweaking the grammar in separate rules that return AST nodes obviously makes all this clearer and potentially easier to reason about.

**Comment by PuerkitoBio** [comment]
Just to be clear, labels **are** allowed in subexpressions, but they are available to code blocks in those subexpressions only. It's very similar to lexical scoping in programming languages, if that helps. Open a new scope and declare a var, that var is visible within that scope, but not in its parent scope.

**Comment by alecthomas** [comment]
Yep, understood. I see that this is the same way PEG.js works.

Using indexes would work, but would be fragile to changes in the grammar though wouldn't it? Though I see that some PEG.js examples use [this same approach](https://github.com/pegjs/pegjs/blob/master/examples/javascript.pegjs#L554).

I guess that's the way it is! Thanks!
