### ISSUE TITLE
Encoding error REPLACEMENT CHARACTER

### ISSUE THREAD

**Issue by RedSkotina** [PuerkitoBio/pigeon#12]
i have rule 
Comment = (("//" (!NL .)* &NL)  /  ("/*" (!"*/" .)* "*/"))  
and take error  `rule Comment: invalid encoding` on source which contain REPLACEMENT CHARACTER (utf-8 0xEF 0xBF 0xBD) (�)

I look up workaround.

**Comment by PuerkitoBio** [comment]
Hello,

You have that error when you try to parse an input file that should conform to your pigeon (rules) file? Or when trying to build the parser from your rules file? That error indicates that your input is not valid utf8, and depending on the step at which it occurs, the invalid input may be your grammar or the file you're trying to parse with that grammar.

Martin

**Comment by RedSkotina** [comment]
I get this error while parsing my input file which contain this ACTUAL character inserted by user editor

>  /* blah blah blah � */
if  remove this character from line then all fine. I look for any method for catching this error.
REPLACEMENT CHARACTER is not valid utf-8?

**Comment by PuerkitoBio** [comment]
Replacement character is the character returned when the input contains
invalid utf8.

**Comment by RedSkotina** [comment]
but my input file contain hex sequence 0xEF 0xBF 0xBD . user save this sequence in the file.
i cannot parse this sequence?

**Comment by PuerkitoBio** [comment]
Indeed, if the input contained the actual replacement char, it was incorrectly detected as an encoding error. It's fixed in the branch `fix-replacement-char`, could you give it a try and let me know if all's good for you? I'll merge on master after that.

Thanks,
Martin

**Comment by RedSkotina** [comment]
yes. error has gone away. thanks
