### ISSUE TITLE
No stack trace for panics in handlers

### ISSUE THREAD

**Issue by alecthomas** [PuerkitoBio/pigeon#2]
I have a bug somewhere in my code resulting in a nil pointer dereference, but unfortunately I have no idea where it is because pigeon converts panics into errors:

```
%!s(PANIC=runtime error: invalid memory address or nil pointer dereference)
```

Some way of not capturing panics would be nice I think.

**Comment by PuerkitoBio** [comment]
Agreed, I added the `-no-recover` flag to the pigeon tool, and the `Recover(bool)` option func to the generated parser, so it can be turned off when called like this:

```
result, err := Parse("filename", data, Recover(false))
```

**Comment by alecthomas** [comment]
Brilliant, thanks!
