### ISSUE TITLE
Feature request: aggregate values for labels appearing multiple times in expression

### ISSUE THREAD

**Issue by erjoalgo** [PuerkitoBio/pigeon#6]
A lot of boilerplate code is needed to extract a list of elements that appear in different parts of an expression. 

If the same label appears in more than once in an expression, the underlying value of that label should be an []interface{}, where each element is the value of the labeled field in the order it appears in the text. 

Additionally, if a label appears within a repeating subexpression, the resulting list should contain the repeating elements (as opposed to a list of the repeating elements).

For example, the rule:
```golang
non_empty_string_array <- "[" elms:StringLit (_ "," _ elms:StringLit)* _ "]" _ ";" {
return elms, nil}
```

when parsing this input:
```
[ "a", "b", "c" ]
```
should return a slice of length 3.

This would make it possible to solve a lot of very common problems without any code at all, and make this great project even more powerful.

**Comment by PuerkitoBio** [comment]
I can see how that seems appealing, but this wouldn't work like this - in that example, the first elms is not in the same scope as the 2nd one (parentheses open a new scope, the expression that is at the same level as the first elms is actually the whole zero-or-many repeating expression `("," elms:StringLit)*`.

There could be syntactic sugar added to the grammar, but I kept it relatively simple and although that means maybe more code blocks and type conversions, it makes for straightforward and easy to understand peg files (well, once the whole PEG thing if fully grasped, which I admit is not so simple!).

**Comment by erjoalgo** [comment]
Yeah, I understand, but I think it can be made to work. Each sub-expression would be associated with a map of labels to values, and these labels are recursively aggregated in higher expressions. In the "base case" of the above examplethe Seq expression `_ "," _ elms:StringLit` would normally produce a map where elms is bound to the 3rd element, a StringLit. But then the zero-or-many expression:

`(_ "," _ elms:StringLit)*` 

would aggregate each labeled value to a slice. So elms for this zero-or-many would be a []StringLit underlying type.

Then, again, in the Seq expression, 

`"[" elms:StringLit (_ "," _ elms:StringLit)* _ "]" _ ";"`

since elms appears more than once, (in the 2nd and 3rd positions after zero-or-many is recursively resolved), then Seq would aggregate those values together into a slice. Although I agree that the resulting value of elms[0] would be StringLit, and elms[1] would be []StringList. But at least it would be easier to specify more declaratively which elements we want to capture. It's just an idea that I know would require some work, just wanted to put it out there.

**Comment by PuerkitoBio** [comment]
It could be made to work, but I expect those customizations to add a lot of complexity for very specific use-cases. I think it could be done outside of pigeon, somewhat similar to a macro preprocessor, and it could generate a valid pigeon grammar as output. Or just handle it on a case-by-case basis with code blocks. I don't think I'd want to add that feature in pigeon, to be honest.
